name: dataset-morocco-dz-2024
channels:
  - conda-forge
  - davasey
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=1.5.1
  - matplotlib
  - ipykernel
  - jupyter
  - openpyxl
  - pypdf
  - cmcrameri
  - xlrd
  - rpy2
  - r-irkernel
  - r-isoplotr=5.2
  - pip
  - pip:
      - git+https://github.com/dyvasey/geoscripts
