name: dataset-morocco-dz-2024
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - rasterio
  - matplotlib
  - ipykernel
  - jupyter
  - openpyxl
  - pypdf
  - cmcrameri
  - glasbey
  - seaborn
  - xlrd
  - scikit-learn
  - pip
  - pip:
      - git+https://github.com/dyvasey/geoscripts.git@dz
